name: bmt_backend
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^1.0.2
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  keyboard_avoider: ^0.1.2
  url_launcher: ^5.7.8
  fluttertoast: ^4.0.0
  ##firebase_messaging: ^6.0.16
  connectivity: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - Assets/User.png
    - Assets/ChatLogo/drawable-xhdpi/ChatLogo.png
